apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: humor-game-cluster
servers: 1
agents: 2
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
registries:
  use: 
    - k3d-k3d-registry:5001
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*

